### ISSUE TITLE
No global average pooling layer

### ISSUE THREAD

**Issue by tiendungchs** [romulus0914/NASBench-PyTorch#10]
In the original implementation, I see a global average pooling layer between the last stack and the dense layer
`    # Global average pool
    if config['data_format'] == 'channels_last':
      net = tf.reduce_mean(net, [1, 2])
    elif config['data_format'] == 'channels_first':
      net = tf.reduce_mean(net, [2, 3])
    else:
      raise ValueError('invalid data_format')
`
Am I missing something or there is no global average pooling layer in this version?
https://github.com/romulus0914/NASBench-PyTorch/blob/37bc332bc6802e0375d8cca839d54f47524487fb/nasbench_pytorch/model/model.py#L74
Thanks

**Comment by tiendungchs** [comment]
https://github.com/romulus0914/NASBench-PyTorch/blob/37bc332bc6802e0375d8cca839d54f47524487fb/nasbench_pytorch/model/model.py#L81
Now I see it. Sorry I didn't look carefully

**Comment by gabikadlecova** [comment]
Glad the issue was resolved quickly :-)
